### ISSUE TITLE
Consider using GitHub Actions' create-pull-request action

### ISSUE THREAD

**Issue by alexanderilyin** [deep-space-cartel/devcontainers-features#16]
.github/workflows/release.yaml (1): Line range hint 31-47 

The current implementation for creating documentation PRs uses manual git commands. Consider using the peter-evans/create-pull-request action for a more maintainable solution.

Example implementation:

```
- name: Create PR for Documentation
  uses: peter-evans/create-pull-request@v7
  with:
    commit-message: 'Automated documentation update [skip ci]'
    title: 'Automated documentation update'
    branch: automated-documentation-update-${{ github.run_id }}
    delete-branch: true
```
